/**
 * templates.ts — canonical block content for the agent-harness
 * installer. Closes Phase 2 of the agent-harness plan.
 *
 * Everything here is a static string — the installer treats each
 * template as the source of truth, computes an HMAC, and writes a
 * wrapped block into the target file. The drift-detection test in
 * `tests/InstallTemplatePin.test.ts` asserts that any file that
 * carries a ctxloom-managed block matches the canonical content
 * verbatim (modulo the user's content outside the markers).
 *
 * Naming convention:
 *   - The CTXLOOM-RULES block lives in CLAUDE.md / AGENTS.md / GEMINI.md
 *     (one block per file; same content across hosts so the rules
 *     stay consistent — agents on different hosts see the same
 *     instructions). Future per-host content can split into
 *     CTXLOOM-RULES-CLAUDE / -GEMINI / -CURSOR if needed.
 *   - The session-start.sh file is fully ctxloom-managed; we replace
 *     the entire file (with a header note that ctxloom owns it) on
 *     each install — no in-file markers needed.
 *   - hooks.json is a JSON file; we merge with existing entries by
 *     matcher key, similar to how runInit() merges .mcp.json.
 */

/**
 * The canonical agent-rules block. Identical content shipped to
 * CLAUDE.md, AGENTS.md, GEMINI.md so cross-host agents see the same
 * guidance. References ctx_get_minimal_context — the orientation
 * anchor from Phase 1.
 */
export const RULES_BLOCK_NAME = 'CTXLOOM-RULES';

export const RULES_BLOCK_CONTENT = `## MCP Tools: ctxloom

**IMPORTANT: This project has a knowledge graph. ALWAYS use the
ctxloom MCP tools BEFORE Grep/Glob/Read to explore the codebase.**
The graph is faster, cheaper (fewer tokens), and gives you
structural context (callers, dependents, test coverage) that file
scanning cannot.

### Start every workflow with \`ctx_get_minimal_context\`

The first MCP call into ctxloom should always be
\`ctx_get_minimal_context(task="<what you're about to do>")\`. It
returns ~150 tokens of orientation plus a task-aware
\`suggested_first_tool\` you should call next instead of guessing.

### When to use graph tools FIRST

- **Code review**: \`ctx_detect_changes\` + \`ctx_get_review_context\`
  instead of reading whole files
- **Understanding impact**: \`ctx_blast_radius\` + \`ctx_get_affected_flows\`
  instead of manually tracing imports
- **Refactor planning**: \`ctx_get_call_graph(direction: 'callers')\`
  + \`ctx_refactor_preview\` before any rename
- **Architecture questions**: \`ctx_architecture_overview\`,
  \`ctx_community_list\`, \`ctx_hub_nodes\`
- **Finding code**: \`ctx_search\` or \`ctx_full_text_search\` instead
  of \`Grep\`

Fall back to Grep/Glob/Read **only** when the graph doesn't cover
what you need.

### Follow the \`next_tool_suggestions\` in every response

Every budget-wrapped ctxloom response includes
\`meta.next_tool_suggestions\` — author-curated follow-ups with
\`why\` reasoning and \`estimated_tokens\` per entry. Pick from
those instead of guessing.

### Token-budget protocol

- Target: ≤8 tool calls per task, ≤2000 total tokens of graph context
- Pass \`max_response_tokens\` on calls that might return large
  responses; the budget surface returns skeletons instead of dumping
- Use \`response_format: 'skeleton'\` when you know you only need
  signatures, not bodies

### Key tools at a glance

| Tool | Use when |
|------|----------|
| \`ctx_get_minimal_context\` | START HERE — orientation anchor |
| \`ctx_detect_changes\` | Reviewing code changes; risk-scored |
| \`ctx_get_review_context\` | Token-efficient review snippets |
| \`ctx_blast_radius\` | Blast radius of a change |
| \`ctx_get_affected_flows\` | Execution paths impacted |
| \`ctx_get_call_graph\` | Callers / callees of a symbol |
| \`ctx_search\` / \`ctx_full_text_search\` | Find code |
| \`ctx_architecture_overview\` | High-level codebase map |
| \`ctx_refactor_preview\` / \`ctx_apply_refactor\` | Plan a rename |

### Hooks keep the graph fresh

\`ctxloom init\` installed a PostToolUse hook on \`Write|Edit\` that
runs \`ctxloom update --incremental --quiet\` — so the graph is
always up to date when you query it. No "did the index update yet?"
guessing.`;

/**
 * Header line written at the top of session-start.sh so users
 * understand it's ctxloom-managed.
 */
export const SESSION_START_HEADER = `#!/usr/bin/env bash
# ctxloom — agent-harness session-start hook
# Generated by \`ctxloom init\`. Re-run \`ctxloom init\` to update.
# Manual edits will be overwritten on the next install.

set -e
`;

/**
 * The body of session-start.sh — POSIX-portable shell that probes
 * the graph and prints orientation to stdout (which Claude Code
 * captures and injects into the agent's session context).
 *
 * Performance: target <500ms total. Uses \`ctxloom status --json\`
 * (cached, sub-100ms) for the stats line. Skips entirely when no
 * graph DB is present (cold-install case).
 *
 * Security: no user-controllable variables echoed. \`$DB\` is a
 * hard-coded relative path that resolves relative to the user's
 * cwd at session-start time (Claude Code sets cwd to the project
 * root before running hooks).
 */
export const SESSION_START_BODY = `DB=".ctxloom/graph.db"

if [ -f "$DB" ]; then
  # \`ctxloom status --json\` is cached + sub-100ms — keeps the hook
  # under its 2s timeout even on cold disk.
  STATS=$(ctxloom status --json 2>/dev/null || echo '{"nodes":0,"edges":0}')
  NODES=$(echo "$STATS" | grep -oE '"nodes":\\s*[0-9]+' | grep -oE '[0-9]+' || echo "?")
  EDGES=$(echo "$STATS" | grep -oE '"edges":\\s*[0-9]+' | grep -oE '[0-9]+' || echo "?")

  cat <<EOF
[ctxloom] Knowledge graph ready (\${NODES} nodes, \${EDGES} edges).

Start every workflow with \\\`ctx_get_minimal_context(task="...")\\\`.
It returns ~150 tokens of orientation + a task-aware
suggested_first_tool. Follow the meta.next_tool_suggestions on
every response.

Prefer ctxloom MCP tools over Grep/Glob/Read:
  - ctx_detect_changes for code review
  - ctx_blast_radius / ctx_get_call_graph before refactoring
  - ctx_architecture_overview for orientation
EOF
else
  cat <<EOF
[ctxloom] No knowledge graph found here.
Run: ctxloom build

Then restart this session to enable graph-powered queries.
EOF
fi
`;

/**
 * Full session-start.sh content (header + body). Written verbatim
 * during \`ctxloom init\`.
 */
export const SESSION_START_FULL = SESSION_START_HEADER + '\n' + SESSION_START_BODY;

/**
 * Canonical hooks.json content. Merge semantics: the installer reads
 * any existing hooks.json, merges the SessionStart + PostToolUse
 * entries by their matcher, and writes back. Other entries are
 * preserved.
 *
 * @public
 */
export interface HooksJsonShape {
  SessionStart?: Array<{ matcher: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>;
  PostToolUse?: Array<{ matcher: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>;
  [key: string]: unknown;
}

export const CTXLOOM_HOOK_ENTRIES = {
  SessionStart: {
    matcher: '',
    hooks: [{ type: 'command', command: '.claude/hooks/session-start.sh', timeout: 2 }],
  },
  PostToolUse: {
    matcher: 'Write|Edit',
    hooks: [
      {
        type: 'command',
        command: 'ctxloom update --incremental --quiet',
        timeout: 30,
      },
    ],
  },
};
