/**
 * templates.ts — canonical block content for the agent-harness
 * installer. Closes Phase 2 of the agent-harness plan.
 *
 * Everything here is a static string — the installer treats each
 * template as the source of truth, computes an HMAC, and writes a
 * wrapped block into the target file. The drift-detection test in
 * `tests/InstallTemplatePin.test.ts` asserts that any file that
 * carries a ctxloom-managed block matches the canonical content
 * verbatim (modulo the user's content outside the markers).
 *
 * Naming convention:
 *   - The CTXLOOM-RULES block lives in CLAUDE.md / AGENTS.md / GEMINI.md
 *     (one block per file; same content across hosts so the rules
 *     stay consistent — agents on different hosts see the same
 *     instructions). Future per-host content can split into
 *     CTXLOOM-RULES-CLAUDE / -GEMINI / -CURSOR if needed.
 *   - The session-start.sh file is fully ctxloom-managed; we replace
 *     the entire file (with a header note that ctxloom owns it) on
 *     each install — no in-file markers needed.
 *   - hooks.json is a JSON file; we merge with existing entries by
 *     matcher key, similar to how runInit() merges .mcp.json.
 */

/**
 * The canonical agent-rules block. Identical content shipped to
 * CLAUDE.md, AGENTS.md, GEMINI.md so cross-host agents see the same
 * guidance. References ctx_get_minimal_context — the orientation
 * anchor from Phase 1.
 */
export const RULES_BLOCK_NAME = 'CTXLOOM-RULES';

export const RULES_BLOCK_CONTENT = `## MCP Tools: ctxloom

**IMPORTANT: This project has a knowledge graph. ALWAYS use the
ctxloom MCP tools BEFORE Grep/Glob/Read to explore the codebase.**
The graph is faster, cheaper (fewer tokens), and gives you
structural context (callers, dependents, test coverage) that file
scanning cannot.

### Start every workflow with \`ctx_get_minimal_context\`

The first MCP call into ctxloom should always be
\`ctx_get_minimal_context(task="<what you're about to do>")\`. It
returns ~150 tokens of orientation plus a task-aware
\`suggested_first_tool\` you should call next instead of guessing.

### When to use graph tools FIRST

- **Code review**: \`ctx_detect_changes\` + \`ctx_get_review_context\`
  instead of reading whole files
- **Understanding impact**: \`ctx_blast_radius\` + \`ctx_get_affected_flows\`
  instead of manually tracing imports
- **Refactor planning**: \`ctx_get_call_graph(direction: 'callers')\`
  + \`ctx_refactor_preview\` before any rename
- **Architecture questions**: \`ctx_architecture_overview\`,
  \`ctx_community_list\`, \`ctx_hub_nodes\`
- **Finding code**: \`ctx_search\` or \`ctx_full_text_search\` instead
  of \`Grep\`

Fall back to Grep/Glob/Read **only** when the graph doesn't cover
what you need.

### Follow the \`next_tool_suggestions\` in every response

Every budget-wrapped ctxloom response includes
\`meta.next_tool_suggestions\` — author-curated follow-ups with
\`why\` reasoning and \`estimated_tokens\` per entry. Pick from
those instead of guessing.

### Token-budget protocol

- Target: ≤8 tool calls per task, ≤2000 total tokens of graph context
- Pass \`max_response_tokens\` on calls that might return large
  responses; the budget surface returns skeletons instead of dumping
- Use \`response_format: 'skeleton'\` when you know you only need
  signatures, not bodies

### Key tools at a glance

| Tool | Use when |
|------|----------|
| \`ctx_get_minimal_context\` | START HERE — orientation anchor |
| \`ctx_detect_changes\` | Reviewing code changes; risk-scored |
| \`ctx_get_review_context\` | Token-efficient review snippets |
| \`ctx_blast_radius\` | Blast radius of a change |
| \`ctx_get_affected_flows\` | Execution paths impacted |
| \`ctx_get_call_graph\` | Callers / callees of a symbol |
| \`ctx_search\` / \`ctx_full_text_search\` | Find code |
| \`ctx_architecture_overview\` | High-level codebase map |
| \`ctx_refactor_preview\` / \`ctx_apply_refactor\` | Plan a rename |

### Hooks keep the graph fresh

\`ctxloom init\` installed a PostToolUse hook on \`Write|Edit\` that
runs \`ctxloom update --incremental --quiet\` — so the graph is
always up to date when you query it. No "did the index update yet?"
guessing.`;

/**
 * Header line written at the top of session-start.sh so users
 * understand it's ctxloom-managed.
 */
export const SESSION_START_HEADER = `#!/usr/bin/env bash
# ctxloom — agent-harness session-start hook
# Generated by \`ctxloom init\`. Re-run \`ctxloom init\` to update.
# Manual edits will be overwritten on the next install.

set -e
`;

/**
 * The body of session-start.sh — POSIX-portable shell that probes
 * the graph and prints orientation to stdout (which Claude Code
 * captures and injects into the agent's session context).
 *
 * Performance: target <500ms total. Uses \`ctxloom status --json\`
 * (cached, sub-100ms) for the stats line. Skips entirely when no
 * graph DB is present (cold-install case).
 *
 * Security: no user-controllable variables echoed. \`$DB\` is a
 * hard-coded relative path that resolves relative to the user's
 * cwd at session-start time (Claude Code sets cwd to the project
 * root before running hooks).
 */
export const SESSION_START_BODY = `DB=".ctxloom/graph.db"

if [ -f "$DB" ]; then
  # \`ctxloom status --json\` is cached + sub-100ms — keeps the hook
  # under its 2s timeout even on cold disk.
  STATS=$(ctxloom status --json 2>/dev/null || echo '{"nodes":0,"edges":0}')
  NODES=$(echo "$STATS" | grep -oE '"nodes":\\s*[0-9]+' | grep -oE '[0-9]+' || echo "?")
  EDGES=$(echo "$STATS" | grep -oE '"edges":\\s*[0-9]+' | grep -oE '[0-9]+' || echo "?")

  cat <<EOF
[ctxloom] Knowledge graph ready (\${NODES} nodes, \${EDGES} edges).

Start every workflow with \\\`ctx_get_minimal_context(task="...")\\\`.
It returns ~150 tokens of orientation + a task-aware
suggested_first_tool. Follow the meta.next_tool_suggestions on
every response.

Prefer ctxloom MCP tools over Grep/Glob/Read:
  - ctx_detect_changes for code review
  - ctx_blast_radius / ctx_get_call_graph before refactoring
  - ctx_architecture_overview for orientation
EOF
else
  cat <<EOF
[ctxloom] No knowledge graph found here.
Run: ctxloom build

Then restart this session to enable graph-powered queries.
EOF
fi
`;

/**
 * Full session-start.sh content (header + body). Written verbatim
 * during \`ctxloom init\`.
 */
export const SESSION_START_FULL = SESSION_START_HEADER + '\n' + SESSION_START_BODY;

/**
 * Canonical hooks.json content. Merge semantics: the installer reads
 * any existing hooks.json, merges the SessionStart + PostToolUse
 * entries by their matcher, and writes back. Other entries are
 * preserved.
 *
 * @public
 */
export interface HooksJsonShape {
  SessionStart?: Array<{ matcher: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>;
  PostToolUse?: Array<{ matcher: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>;
  [key: string]: unknown;
}

export const CTXLOOM_HOOK_ENTRIES = {
  SessionStart: {
    matcher: '',
    hooks: [{ type: 'command', command: '.claude/hooks/session-start.sh', timeout: 2 }],
  },
  PostToolUse: {
    matcher: 'Write|Edit',
    hooks: [
      {
        type: 'command',
        command: 'ctxloom update --incremental --quiet',
        timeout: 30,
      },
    ],
  },
};

// ─── Phase 4d: Cross-agent host matrix ───────────────────────────────

/**
 * Per-host adapter — knows the file path + format for the rule content.
 *
 * The Markdown hosts (CLAUDE.md / AGENTS.md / GEMINI.md / CONVENTIONS.md /
 * copilot-instructions.md) carry the canonical RULES_BLOCK_CONTENT
 * wrapped in HMAC markers. The native-format hosts (.cursorrules /
 * .windsurfrules use YAML) need a transcoded body but the same
 * underlying instructions.
 *
 * @public
 */
export interface HostAdapter {
  /** Slug used on the --host CLI flag. */
  id: string;
  /** Relative file path written under the project root. */
  path: string;
  /** Whether this host is included in the default install (no --host flag). */
  defaultEnabled: boolean;
  /**
   * Render the FULL file content for this host, given the canonical
   * rules text. Returns the bytes that will land on disk.
   */
  render(): string;
  /**
   * Verify on-disk content matches what `render()` would produce now.
   * Used for idempotency checks. Markdown adapters defer to HMAC
   * block extraction; YAML/JSON adapters compare verbatim.
   */
  isCanonical(currentContent: string): boolean;
}

/**
 * Strip Markdown formatting that's noise in a plain-text rules file
 * (CONVENTIONS.md works as Markdown, but Aider/Cursor users often
 * scan with plain `cat`; the rendered file should read cleanly without
 * a viewer).
 */
function plainBody(): string {
  return RULES_BLOCK_CONTENT
    .replace(/^##\s+/gm, '')           // strip h2 markers
    .replace(/^###\s+/gm, '')          // strip h3 markers
    .replace(/^####\s+/gm, '')         // strip h4 markers
    .replace(/\*\*(.*?)\*\*/g, '$1')   // strip bold
    .replace(/`([^`]+)`/g, '$1');      // strip code fences
}

/**
 * Cursor: `.cursorrules` is documented as plain text (Cursor's own
 * docs). YAML frontmatter is supported for some Cursor versions but
 * the plain-text fallback is universal. Ship plain.
 */
const CURSOR_HEADER = `# ctxloom — Cursor agent rules
# Generated by \`ctxloom init --host=cursor\`. Re-run to update.

`;

/**
 * Aider: \`CONVENTIONS.md\` is Markdown. Aider parses it as project
 * conventions context that's automatically injected into every chat.
 */
const AIDER_HEADER = `# Project Conventions

Generated by \`ctxloom init --host=aider\`. Re-run to update.

`;

/**
 * GitHub Copilot: \`.github/copilot-instructions.md\` is Markdown.
 * Copilot picks it up automatically when the file exists in the repo.
 */
const COPILOT_HEADER = `# ctxloom — GitHub Copilot instructions

Generated by \`ctxloom init --host=copilot\`. Re-run to update.

`;

/**
 * Windsurf: \`.windsurfrules\` is plain text (similar to Cursor's).
 */
const WINDSURF_HEADER = `# ctxloom — Windsurf agent rules
# Generated by \`ctxloom init --host=windsurf\`. Re-run to update.

`;

/**
 * Available host adapters. Map keyed by `id` (the --host CLI value).
 *
 * Default-enabled hosts (Claude / AGENTS / Gemini) are written on
 * every `ctxloom init` for back-compat. Non-default hosts (Cursor /
 * Aider / Copilot / Windsurf) require explicit \`--host=<id>\` opt-in
 * because users typically only have one or two agent hosts installed
 * and we don't want to bloat their repo with files they don't use.
 *
 * @public
 */
export const HOST_ADAPTERS: HostAdapter[] = [
  // Note: claude / agents / gemini are NOT defined as HostAdapters in
  // this list — they predate the matrix and live in their own writeRulesBlock
  // path with HMAC-wrapped Markdown blocks. Future refactor may unify.
  {
    id: 'cursor',
    path: '.cursorrules',
    defaultEnabled: false,
    render: () => CURSOR_HEADER + plainBody() + '\n',
    isCanonical(current) {
      return current === this.render();
    },
  },
  {
    id: 'aider',
    path: 'CONVENTIONS.md',
    defaultEnabled: false,
    render: () => AIDER_HEADER + RULES_BLOCK_CONTENT + '\n',
    isCanonical(current) {
      return current === this.render();
    },
  },
  {
    id: 'copilot',
    path: '.github/copilot-instructions.md',
    defaultEnabled: false,
    render: () => COPILOT_HEADER + RULES_BLOCK_CONTENT + '\n',
    isCanonical(current) {
      return current === this.render();
    },
  },
  {
    id: 'windsurf',
    path: '.windsurfrules',
    defaultEnabled: false,
    render: () => WINDSURF_HEADER + plainBody() + '\n',
    isCanonical(current) {
      return current === this.render();
    },
  },
];

/**
 * Look up a host adapter by id. Returns undefined for unknown hosts.
 *
 * @public
 */
export function getHostAdapter(id: string): HostAdapter | undefined {
  return HOST_ADAPTERS.find((h) => h.id === id);
}

/**
 * Valid --host CLI values (in addition to "all").
 *
 * @public
 */
export const SUPPORTED_HOST_IDS = HOST_ADAPTERS.map((h) => h.id);
