import { ToolRegistry } from './registry.js';
import type { ServerContext } from './context.js';
import { registerSearchTool } from './search.js';
import { registerFileTool } from './file.js';
import { registerContextPacketTool } from './context-packet.js';
import { registerCallGraphTool } from './call-graph.js';
import { registerDefinitionTool } from './definition.js';
import { registerRulesTool } from './rules.js';
import { registerSimilarFilesTool } from './similar-files.js';
import { registerStatusTool } from './status.js';
import { registerBlastRadiusTool } from './blast-radius.js';
import { registerHubNodesTool } from './hub-nodes.js';
import { registerBridgeNodesTool } from './bridge-nodes.js';
import { registerCommunityListTool } from './community-list.js';
import { registerArchitectureOverviewTool } from './architecture-overview.js';
import { registerKnowledgeGapsTool } from './knowledge-gaps.js';
import { registerSurprisingConnectionsTool } from './surprising-connections.js';
import { registerWikiGenerateTool } from './wiki-generate.js';
import { registerGraphExportTool } from './graph-export.js';
import { registerGitDiffReviewTool } from './git-diff-review.js';
import { registerRefactorPreviewTool } from './refactor-preview.js';
import { registerExecutionFlowTool } from './execution-flow.js';
import { registerCrossRepoSearchTool } from './cross-repo-search.js';
import { registerApplyRefactorTool } from './apply-refactor.js';
import { registerDetectChangesTool } from './detect-changes.js';
import { registerFullTextSearchTool } from './full-text-search.js';
import { registerSuggestedQuestionsTool } from './suggested-questions.js';
import { registerGetWorkflowTool } from './get-workflow.js';
import { registerGraphSnapshotTool } from './graph-snapshot.js';
import { registerGraphDiffTool } from './graph-diff.js';
import { registerFindLargeFunctionsTool } from './find-large-functions.js';

export function createToolRegistry(ctx: ServerContext): ToolRegistry {
  const registry = new ToolRegistry();
  registerSearchTool(registry, ctx);
  registerFileTool(registry, ctx);
  registerContextPacketTool(registry, ctx);
  registerCallGraphTool(registry, ctx);
  registerDefinitionTool(registry, ctx);
  registerRulesTool(registry, ctx);
  registerSimilarFilesTool(registry, ctx);
  registerStatusTool(registry, ctx);
  registerBlastRadiusTool(registry, ctx);
  registerHubNodesTool(registry, ctx);
  registerBridgeNodesTool(registry, ctx);
  registerCommunityListTool(registry, ctx);
  registerArchitectureOverviewTool(registry, ctx);
  registerKnowledgeGapsTool(registry, ctx);
  registerSurprisingConnectionsTool(registry, ctx);
  registerWikiGenerateTool(registry, ctx);
  registerGraphExportTool(registry, ctx);
  registerGitDiffReviewTool(registry, ctx);
  registerRefactorPreviewTool(registry, ctx);
  registerExecutionFlowTool(registry, ctx);
  registerCrossRepoSearchTool(registry, ctx);
  registerApplyRefactorTool(registry, ctx);
  registerDetectChangesTool(registry, ctx);
  registerFullTextSearchTool(registry, ctx);
  registerSuggestedQuestionsTool(registry, ctx);
  registerGetWorkflowTool(registry, ctx);
  registerGraphSnapshotTool(registry, ctx);
  registerGraphDiffTool(registry, ctx);
  registerFindLargeFunctionsTool(registry, ctx);
  return registry;
}
